[build]
  command = "npm run build"
  publish = "dist/angular-ecomm/browser"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime"

  # Si necesitas configurar entradas para el plugin (inputs):
  # [plugins.inputs]
  # Aquí puedes agregar configuraciones específicas si el plugin las soporta.
